version: '3'
services:
  qbittorrent:
    image: epicmorg/qbittorrent:latest
    restart: always
    container_name: qbittorrent
    ports:
      - "0.0.0.0:8282:8282"
    volumes:
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
      - /etc/letsencrypt:/etc/letsencrypt
      - /opt/qbittorrent/profiles:/opt/qbittorrent/profiles
    tmpfs:
      - /tmp
    environment:
      - QBT_PROFILE_NAME=docker

